[POSTGRES_QUERIES]
# basic queries to access rows
CREATE_TABLE = """CREATE TABLE {tablename} (
  id SERIAL PRIMARY KEY,
  imdbid SERIAL,
  title VARCHAR,
  genres TEXT[],
  ratings REAL,
  users_rated SERIAL
  )"""
INSERT_INTO = """INSERT INTO movies(id, imdbid, title, genres,
ratings, users_rated) VALUES(%s, %s, %s, %s, %s, %s)"""
SELECT_EXISTS = "SELECT EXISTS(SELECT * FROM information_schema.tables WHERE table_name=%s)"
GET_BY_ID = "SELECT * FROM {tablename} WHERE id=%s"
SELECT_IF_UPVOTE = "SELECT * FROM {tablename} WHERE genres && %s"
SELECT_IF_DOWNVOTE = "SELECT * FROM {tablename} WHERE NOT genres && %s"
# validate database if already exists 
CHECK_NUMBER_OF_ROWS = "SELECT COUNT(id) FROM {tablename}"
CHECK_NUMBER_OF_COLS = """SELECT COUNT(*) FROM information_schema.columns WHERE
table_name='{tablename}'"""
