channel_keywords = ["Gamer Nexus", "xQc", "pewdiepie", "ninja"]
title_keywords = ['call of duty', "battlefield", "nfs", "forza horizon"]
description_keywords = [""]
genre_keywords = ['racing', "fps", "mmo", "rpg"]
